version: '3'
services:
  softexpert_db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123123qwe#@#
      POSTGRES_DB: softexpert_market
    ports:
      - 5432:5432
    volumes:
      - ./docker/data:/var/lib/postgresql/data
    networks:
      - softexpert_network

  softexpert_php:
    build:
      context: .
      dockerfile: Dockerfile.php
      args: 
        - POSTGRES_DEV_PACKAGE=libpq-dev
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    networks:
      - softexpert_network

  softexpert_vue:
    build:
      context: .
      dockerfile: Dockerfile.vue
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./resources:/app
    working_dir: /app
    networks:
      - softexpert_network

networks:
  softexpert_network:
    driver: bridge
